baseURL = "/"
languageCode = "fr-FR"
title = "Les Jardins Botaniques de Haut Bretagne"
theme = "jardin"

DefaultContentLanguage = "fr"

[languages]

  [languages.fr]
    title = "Jardins Botaniques de Haut Bretagne"
    weight = 1

  [[languages.fr.menu.quicklinks]]
    title = "nos horaires"
    url = "/info/#horaires"
    summary = ""  

  [languages.en]
    title = "Botanical Gardens of Upper Brittany"
    weight = 2

    [[languages.en.menu.quicklinks]]
      title = "Our opening hours"
      url = "/en/info/#horaires"
      summary = ""  


  [languages.es]
    title = "jardines botánicos de alta bretaña"
    weight = 3

    #[[languages.es.menu.quicklinks]]
  #  title = "nuestros horarios"
  #  url = "/info/#horaires"
  #  summary = ""  
#
  #[[languages.es.menu.quicklinks]]
  #  identifier = "sobre"
  #  name = "sobre Hugo"
