DefaultContentLanguage = "fr"
baseURL = "/"
languageCode = "fr-FR"
theme = "jardin"
[languages.en]
contentDir = "content/english"
languageName = "English"
title = "Botanical Gardens of Upper Brittany"
weight = 20
[languages.es]
contentDir = "content/spanish"
languageName = "Spanish"
title = "jardines botánicos de alta bretaña"
weight = 3
[languages.fr]
contentDir = "content/french"
languageName = "Français"
title = "Jardin Botanique de Haut Bretagne"
weight = 10
[[languages.fr.menu.quicklinks]]
post = "quand visiter?"
title = "nos horaires"
url = "/info/#horaires"
[[menu.quicklinks]]
post = "when you can visit"
title = "Our opening hours"
url = "/en/info/#horaires"
