#+TITLE: Editor operation manual for jardinbretagne.com
#+SETUPFILE: ~/.emacs.d/personal/org-html-themes/setup/theme-readtheorg.setup

This document aims to provide exhaustive guidance for editors whose job it is to elaborate the content of this new website for the /Parc Botanique de Haut Bretagne/.

For the technically curious it also provides, at the end, a very cursory overview of the technologies with which it was built.
* Editing existing material
** The editing tools
The site owner and her editors can use the site’s [[https://forestry.io][forestry]] interface both to edit existing material and to create new pages. The final way to access these editing tools remains to be determined.
** What can be edited
Most of the site’s content can be edited. This includes its [[*Menus][menus]], all the content on the [[*Homepage][homepage]], and, of course, the contents of the individual [[*Single Pages][pages]].
** What can’t be edited
At the moment there is no way to edit the content of the footer that’s found at the bottom of every page. You should agree with the developer a final version of this before the site is handed off.

It’s also not possible to change the way the site as a whole *looks*. That’s fixed by the design. This relieves the site owner and her editors of the responsibility to decide how things should look: those decisions have already been taken.

If the site owner or the editors discover that some kind of agreed content looks *broken* when it’s displayed, then this problem should be addressed to the developer.
** What is a page?
When we edit a page in forestry, we see two panels: on the left hand side, a list of toggles and switches; on the right hand side, a text editor. 
**** front matter
The left hand side represents a page’s “front-matter”. These are “settings” for the page. They allow us to set what the large image at the top of the page should be, how the page should be summarised, and other features of the page.
**** content
The right hand side represents the “contents” of a page. This is what is shown in the main body of a page: the main column of text and images.

This is shown by default in a friendly word-processor-like format. The file itself is in a format called [[https://commonmark.org/help/][markdown]]; you can see this source by clicking the three dots in the upper-right corner of the forestry editor and clicking “raw editor” to see what things are being built from. This may sometimes be useful, but should mostly be unnecessary. *However, since some functionality of the site requires the editors to write raw markdown* (see, for example, [[*config.toml][here]]) *I recommend editors take the time to work through this [[https://commonmark.org/help/tutorial/][10-minute markdown tutorial]]* if they don’t already know how to use this very useful markup language.
** Draft mode
All pages have a “draft” property, allowing them to be written up without appearing on the live site. When the page is ready, turn draft mode off, and the page will appear on the site.

** How to edit the website’s elements
*** Menus
The menus are all automatically generated. Different menus are generated from different sources. Some of these menus can be adjusted by the editors.
**** What editable menus are there?
The main menu which runs across the top of every page (the [[*Main (top) menu][main menu]]) and the set of black cards on the homepage (the [[*quicklinks][quicklinks]]) can both be edited. The other menus are all completely automatic and can’t be edited. They will update themselves to reflect changes in the content.
**** Sources of the menus
***** Front matter
As explained [[*What is a page?][above]], all pages have associated “front matter” which is basically the settings for the page. One of these settings is called “menu”: this setting allows the editors to announce that they want the item to appear in the “main” or the “quicklinks” menu. 
***** config.toml
In order to allow linking offsite, or to parts of the site that are not pages, it’s possible to define cards in the ~settings~ file ~config.toml~. In principle it’s possible to add elements to any menu in this file, but the developer’s intention is that it only be used to modify the black ~quicklinks~ on the front page.

The ~quicklinks~ are defined independently for each language - see internationalization - and the editors can add and remove as many as they like, although they should keep an eye on the visual effect this has on the homepage. Sticking to three is probably best, but four or even 5 might work ok.
**** Main (top) menu
This menu is generated exclusively from the [[*Front matter][front-matter]] of the site’s pages. That means that every page whose ~menu~ settings includes the setting ~main~ will show up here. That can mean an awful lot of menu entries! The developer would *strongly* recommend aiming to minimize the number of entries along this top bar to 4 or 5: it’s important to make the initial choices of users as simple as possible. If the editors want to emphasise some content, they can use [[*quicklinks][quicklinks]] or [[*feature cards][feature cards]]. 

**** quicklinks
The quicklinks - the black ’cards’ on the front page - are designed to allow the editors to highlight particular pages on the website, and to make prominent links off-site, for instance to the garden’s guest booking system.

They are generated from two sources: 
+ from the [[*Front matter][Front matter]] of the site’s various pages (any page with ’quicklinks’ in its ~menu~ setting will show up)
+ from the entries in the ~quicklinks~ list defined underneath each of the site’s languages in [[*config.toml][config.toml]].
*** Homepage

**** carousel
The carousel is configured in the ~settings~ file ~carousel.toml~. See the [[*Images][image guidelines]] for advice about appropriate image sizes. At its full size the carousel is 1800 pixels wide and 800 pixels tall: although it will automatically make whatever images you assign to it fit, if you want the maximum possible control over how the image is displayed you should crop your images in this aspect ratio. But It’s probably better as a rule just to pick normal photographs that look nice and let the software crop them - it will normally be good enough.
**** feature cards
These are the “cards” at the bottom of the homepage: an image, with a little text that can feature links. These are designed to allow a more engaging way to emphasise content than the quicklinks.

These are configured in the [[*Front matter][Front matter]] of the homepages for the different enabled languages. The features for each language must be configured separately (but note that you don’t have to upload the image you want to use multiple times: once you’ve done it once, you’ll find it in forestry’s media library.)

Their settings are fairly self-explanatory. The only tricky thing is that links must be written in the markup language [[*content][markdown]]. See [[*links in markdown][links in markdown]].

**** quicklinks
These are the black boxes just underneath the “welcome” sign. Their configuration is discussed underneath [[*quicklinks][menus]]. It’s very straightforward except that, as with [[*feature cards][feature cards]], any links must be inserted with explicit [[*content][markdown]]; see [[*links in markdown][links in markdown]].
*** Single Pages
Most pages on the site are ~single column pages~. That means that they have some default [[*front matter][front matter]] and that they display whatever [[*content][content]] the editors give them in a single column that runs down the center of the page. *almost all the customization of the website involves adding content to single pages.* You can add as much content as you like to an individual page.
**** featured images
  Every single page can have what’s called a ~hero~ image, called in the page’s front matter a ~featuredImage~. This is shown at the top of the page.
**** summaries and card images
When single pages appear in menus, they often appear with a ~summary~ text. This is automatically generated by default, but quite stupidly; The editors can (and normally should) explicitly define a ~summary~ in each page’s front matter.

When single pages appear in menus, they sometimes appear with an image. This image is derived from the ~featuredImage~ if one exists. If this isn’t desirable for some reason, it’s also possible to add a ~cardImage~; this will be used instead of the ~featuredImage~ for menu cards.
*** Special single pages
**** The info page
The info page is a single-column page, but (because it’s where we store lots of bits of information) it also has a submenu. This submenu is automatically generated from two sources:

+ the headers in the content of the info page
+ the other single column pages in the info folder.
*** list pages
Some pages exist just to show subpages. For instance, ~/evenements/~ shows the three events that are defined, ~hanami~, ~concours~ and ~voyageurs~. These pages are automatically generated based on the front-matter of the pages they show.
*** special list pages
**** hanami, concours and voyageurs
These are a bit complex. Each of them is a bit like a little blog: editors can add new pages 
These are basically little blogs. A new page in ~hanami~, ~concours~ or ~voyageurs~ must have its ~date~ set in the front-matter to correspond to the date when the event took place. *these pages will always show the latest event*, while offering links to previous events.
* Creating new material
** What can be created?
As presently configured, the editors can create *single-column-pages*, *quicklinks* and *feature cards*. everything else is automatically generated.
** Where can single column pages be created?
New single column pages will be recognised and indexed when they are created in the following subdirectories:

+ ~/info~
+ ~/location~
+ ~/garden~
+ ~/evenements/hanami~
+ ~/evenements/concours~
+ ~/evenements/voyageurs~
* Translating the material
** How translation works
Every translation is a kind of “shadow copy” of the default (french) site’s content. Each copy has its own folder: ~content/LANGUAGE~. Every page to be translated must exist in *both* folders, in *identical* places, with an *identical* file name. 

The translation is configured in ~config.toml~, where each language has its own settings (under ~languages~.) This includes the translation of the site’s title and the ~quicklinks~. 

Also in the ~config.toml~ is the option to *disable* certain languages. Any language-codes specified here (“en”, “es” etc) will not be available on the site, even if their translation files are there. This is like “draft mode” for site-translation. When you’re working on a translation, disable it! then when the translation is finished, remove the setting.
* Images
Images should *always* be less than or equal to 1mb in size. This is critical for google search rankings and user experience, as well as the sustainability of the site as currently configured. (We can support many hundreds of 1mb images.)

I recommend starting with the free tool [[https://imageoptim.com/howto.html][imageoptim]] in dealing with this problem. I’m available to help if this proves too difficult to handle. 
* Underlying technologies
All websites are basically made up of three component parts: [[https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5][HTML]] markup, which describes the things to be found on a page;  [[https://developer.mozilla.org/en-US/docs/Web/CSS][style sheets]] which tell browsers how to show those things; and [[https:https://developer.mozilla.org/en-US/docs/Web/JavaScript][javascript]], which can tell the site to do fancy things. 
** markdown
See this [[https://commonmark.org/help/][cheatsheet]] and this  [[https://commonmark.org/help/tutorial/][10-minute markdown tutorial]].
*** links in markdown
~[Link](http://a.com)~






